<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PabrikanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $pabrikans = [
            ['nama_pabrikan' => 'PT ABB Sakti Industri'],
            ['nama_pabrikan' => 'PT Alum Central Mandiri Lestari'],
            ['nama_pabrikan' => 'PT Arlisco Elektrika Perkasa'],
            ['nama_pabrikan' => 'PT Asata Utama'],
            ['nama_pabrikan' => 'PT Bakrie Pipe Industries'],
            ['nama_pabrikan' => 'PT Bambang Djaja'],
            ['nama_pabrikan' => 'PT BICC Berca Cables'],
            ['nama_pabrikan' => 'PT Cannet Elektrik Indonesia'],
            ['nama_pabrikan' => 'PT Central Wire Industrial'],
            ['nama_pabrikan' => 'PT Citra Dian Perkasa'],
            ['nama_pabrikan' => 'PT Citra Mahasurya Industries'],
            ['nama_pabrikan' => 'PT Citra Sanxing Indonesia'],
            ['nama_pabrikan' => 'PT Duta Hita Jaya'],
            ['nama_pabrikan' => 'PT Duta Terang Rubberindo'],
            ['nama_pabrikan' => 'PT EDMI Indonesia'],
            ['nama_pabrikan' => 'PT Ega Tekelindo Prima'],
            ['nama_pabrikan' => 'PT Electra Inti Perkasa'],
            ['nama_pabrikan' => 'PT Entec Electric Indonesia'],
            ['nama_pabrikan' => 'PT Esitas Pacific'],
            ['nama_pabrikan' => 'PT Frilay Beton'],
            ['nama_pabrikan' => 'PT Fuji Dharma Electric'],
            ['nama_pabrikan' => 'PT Gaharu Putra Baja Mandiri'],
            ['nama_pabrikan' => 'PT Graha Sumber Energi'],
            ['nama_pabrikan' => 'PT Guna Era Manufaktura'],
            ['nama_pabrikan' => 'PT Gunabangsa Teknik Industri'],
            ['nama_pabrikan' => 'PT Hexing Technology'],
            ['nama_pabrikan' => 'PT Hezong Elektrik Indonesia'],
            ['nama_pabrikan' => 'PT Hume Sakti Indonesia'],
            ['nama_pabrikan' => 'PT Indoconst Persada'],
            ['nama_pabrikan' => 'PT INES'],
            ['nama_pabrikan' => 'PT Insindo Inti Abadi'],
            ['nama_pabrikan' => 'PT Jaya Beton Indonesia'],
            ['nama_pabrikan' => 'PT Jaya Mandiri Steel'],
            ['nama_pabrikan' => 'PT Jaya Sentrikon Indonesia'],
            ['nama_pabrikan' => 'PT Jembo Cable Company Tbk'],
            ['nama_pabrikan' => 'PT Kabelindo Murni Tbk'],
            ['nama_pabrikan' => 'PT Kalimantan Agung'],
            ['nama_pabrikan' => 'PT Kalla Electrical Systems'],
            ['nama_pabrikan' => 'PT Kencana Teknikatama Sentosa'],
            ['nama_pabrikan' => 'PT Kensaki Polimer Indonesia'],
            ['nama_pabrikan' => 'PT Kentjana Sakti Indonesia'],
            ['nama_pabrikan' => 'PT Kilat Wahana Jenggala'],
            ['nama_pabrikan' => 'PT KMI Wire And Cable Tbk'],
            ['nama_pabrikan' => 'PT Kunango Jantan'],
            ['nama_pabrikan' => 'PT Kurnia Abadi Padang'],
            ['nama_pabrikan' => 'PT Lucky Light Globalindo'],
            ['nama_pabrikan' => 'PT Magnakabel Nusantara'],
            ['nama_pabrikan' => 'PT Makmur Jaya'],
            ['nama_pabrikan' => 'PT Marina Corporindo'],
            ['nama_pabrikan' => 'PT Masrur & Son'],
            ['nama_pabrikan' => 'PT Mastergreen Electric'],
            ['nama_pabrikan' => 'PT Mastra Mulia Mandiri'],
            ['nama_pabrikan' => 'PT Maxima Daya Indonesia'],
            ['nama_pabrikan' => 'PT Mecoindo'],
            ['nama_pabrikan' => 'PT Mega Cipta Bangsa'],
            ['nama_pabrikan' => 'PT Mega Karya Perkasa'],
            ['nama_pabrikan' => 'PT Mega Kharisma Makmur'],
            ['nama_pabrikan' => 'PT Melcoinda'],
            ['nama_pabrikan' => 'PT Morawa Electric Transbuana'],
            ['nama_pabrikan' => 'PT Multi Kencana Niagatama'],
            ['nama_pabrikan' => 'PT Mulya Utama Mandiri Sentosa'],
            ['nama_pabrikan' => 'PT Nurinda'],
            ['nama_pabrikan' => 'PT Nusantara Electric'],
            ['nama_pabrikan' => 'PT Panel Mulia Total'],
            ['nama_pabrikan' => 'PT Perkasa Beton Readymix'],
            ['nama_pabrikan' => 'PT Power Cable Indonesia'],
            ['nama_pabrikan' => 'PT Powerindo Prima Perkasa'],
            ['nama_pabrikan' => 'PT Prima Cable Indo'],
            ['nama_pabrikan' => 'PT Prima Indah Lestari'],
            ['nama_pabrikan' => 'PT Prysmian Cables Indonesia'],
            ['nama_pabrikan' => 'PT Pulung Cable Indonesia'],
            ['nama_pabrikan' => 'PT Pura Mayungan'],
            ['nama_pabrikan' => 'PT Rahmat Kurnia Abadi'],
            ['nama_pabrikan' => 'PT Raja Besi'],
            ['nama_pabrikan' => 'PT Ratu Pola Bumi'],
            ['nama_pabrikan' => 'PT Schneider Indonesia'],
            ['nama_pabrikan' => 'PT Sentosa Sakti Makmur'],
            ['nama_pabrikan' => 'PT Serambi Gayo Sentosa'],
            ['nama_pabrikan' => 'PT Siemens Indonesia'],
            ['nama_pabrikan' => 'PT Sinarindo Wiranusa Elektrik'],
            ['nama_pabrikan' => 'PT Sinergi Beton Utama'],
            ['nama_pabrikan' => 'PT Sintra Sinarindo Elektrik'],
            ['nama_pabrikan' => 'PT Smart Meter Indonesia'],
            ['nama_pabrikan' => 'PT Spindo (Steel Pipe Industry of Indonesia)'],
            ['nama_pabrikan' => 'PT Srirejeki Perdana Steel'],
            ['nama_pabrikan' => 'PT Sucaco, Tbk'],
            ['nama_pabrikan' => 'PT Sumbetri Megah'],
            ['nama_pabrikan' => 'PT Sumi Indo Kabel Tbk'],
            ['nama_pabrikan' => 'PT Surya Putera Pagaruyung'],
            ['nama_pabrikan' => 'PT Suryakabel Cemerlang'],
            ['nama_pabrikan' => 'PT Sutrakabel Intimandiri'],
            ['nama_pabrikan' => 'PT Symphos Electric'],
            ['nama_pabrikan' => 'PT Tiang Beton BRM'],
            ['nama_pabrikan' => 'PT Tiga Pilar Sakato'],
            ['nama_pabrikan' => 'PT Tjakrindo Mas'],
            ['nama_pabrikan' => 'PT Tonggak Ampuh'],
            ['nama_pabrikan' => 'PT Trafoindo Prima Perkasa'],
            ['nama_pabrikan' => 'PT Travesindo Multi Elektrik'],
            ['nama_pabrikan' => 'PT Trias Indra Saputra'],
            ['nama_pabrikan' => 'PT Triputra Electric Abadi'],
            ['nama_pabrikan' => 'PT Tritunggal Swarna'],
            ['nama_pabrikan' => 'PT TS Transformer Indonesia'],
            ['nama_pabrikan' => 'PT Twink Indonesia'],
            ['nama_pabrikan' => 'PT Ulusoy Electric Industry'],
            ['nama_pabrikan' => 'PT Virajaya Riauputra'],
            ['nama_pabrikan' => 'PT Voksel Electric Tbk'],
            ['nama_pabrikan' => 'PT Walsin Lippo Industries'],
            ['nama_pabrikan' => 'PT Wijaya Karya Beton'],
            ['nama_pabrikan' => 'PT ZTT Cable Indonesia']
        ];

        DB::table('pabrikans')->insert($pabrikans);
    }
}
